# Generated by Django 6.0.3 on 2026-05-11 20:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="Quantidade",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Valor total pago (R$)",
            ),
        ),
    ]
