# Generated by Django 6.0.3 on 2026-05-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_recipeitem_sale_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeitem",
            options={
                "verbose_name": "Item do Produto",
                "verbose_name_plural": "Itens do Produto",
            },
        ),
    ]
