# Generated by Django 6.0.3 on 2026-03-31 00:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('month', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Mês')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('expected_units', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unidades previstas')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Previsão de vendas',
                'verbose_name_plural': 'Previsões de vendas',
                'ordering': ['-year', '-month', 'product__name'],
                'unique_together': {('product', 'month', 'year')},
            },
        ),
    ]
