# Generated by Django 6.0.3 on 2026-05-13 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculations",
            "0003_costcalculation_owner_expense_owner_fixedcost_owner_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fixedcost",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Custo fixo",
                "verbose_name_plural": "Custos fixos",
            },
        ),
        migrations.AlterField(
            model_name="fixedcost",
            name="monthly_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Valor mensal (R$)",
            ),
        ),
    ]
